
CREATE DATABASE IF NOT EXISTS PrisonersDilemma;
use PrisonersDilemma;

DROP TABLE IF EXISTS GAME;
DROP TABLE IF EXISTS DECISION;

CREATE TABLE IF NOT EXISTS GAME(
    ID INT NOT NULL  AUTO_INCREMENT PRIMARY KEY,
    NAME_PLAYER_ONE VARCHAR(30) NOT NULL,
    NAME_PLAYER_TWO VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS DECISION(      
    GAME_ID INT NOT NULL,
    ROUND INT NOT NULL,
    DECISION_PLAYER_ONE INT NOT NULL,
    DECISION_PLAYER_TWO INT NOT NULL,
    CONVICTION_PLAYER_ONE INT NOT NULL,
    CONVICTION_PLAYER_TWO INT NOT NULL,
    FOREIGN KEY (GAME_ID) REFERENCES GAME(ID),
     PRIMARY KEY (GAME_ID, ROUND)  
);

create user groep20;
grant all privileges on *.* TO 'groep20'@'%';
flush privileges;

  