INSERT INTO auction (description, minprice) VALUES ('Olieverf op karton, Frans Poelstra - Ingelijst', 1);
INSERT INTO auction (description, minprice) VALUES ('Olieverf en collage op karton, Mr. Homes 1972 - Ingelijst', 1);
INSERT INTO auction (description, minprice) VALUES ('Paul Overhaus (1935-2014) - Algarve - acryl op doek, gesigneerd en gedateerd 2005', 450);
INSERT INTO auction (description, minprice) VALUES ('HAN KRUG - Zeegezicht 1950 - Aquarel', 100);
INSERT INTO auction (description, minprice) VALUES ('Robert Roag - Acryl- en Lakverf op Papier - Tekening G', 36);
INSERT INTO auction (description, minprice) VALUES ('Jan Stolk, Drenkeling, Litho 1967', 35);
INSERT INTO auction (description, minprice) VALUES ('Bijzonder olieverf op doek van een fruitschaal (ingelijst)', 99);
INSERT INTO auction (description, minprice) VALUES ('JAN van DELFT Gr Zeefdruk IRIS Handgesigneerd, Jan van Delft (II) (1950)', 35);
INSERT INTO auction (description, minprice) VALUES ('DODOG SOESENO Zeefdruk VISITING Handgesigneerd, Dodog Soeseno (1954)', 55);
INSERT INTO auction (description, minprice) VALUES ('Wouter Stips - Please, donot let me be misunderstood - 1997', 40);
INSERT INTO auction (description, minprice) VALUES ('Lou Thissen - Carnaval - Gesigneerde zeefdruk - 2003', 40);
INSERT INTO auction (description, minprice) VALUES ('Jan Marinus Letter 1914-1989, Olieverf, Zonder titel', 75);
INSERT INTO auction (description, minprice) VALUES ('Xeno Munninghoff - olieverf - Veluws landschap', 425);
INSERT INTO auction (description, minprice) VALUES ('Martin van Waning - olieverf - Gezicht op Oostvoorne', 395);
INSERT INTO auction (description, minprice) VALUES ('Joop KROPFF (Den Haag 1892 - Delft 1979) - olieverf op paneel - wintergezicht', 545);
INSERT INTO auction (description, minprice) VALUES ('Murano - kuifeend - glas', 12);
INSERT INTO auction (description, minprice) VALUES ('Corry Ammerlaan-van Niekerk - glazen schaal', 14);